#!/bin/bash
declare -a EXTENSION=('*.js' '*.css' '*.png' '*.jpg' '*.bmp' '*.gif');
ULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD)
PENULTIMO_COMMIT=$(git rev-list --max-count=1 HEAD~1)
FILES=$(git diff $ULTIMO_COMMIT $PENULTIMO_COMMIT --name-only)
#echo -e ""
#echo -e "$FILES"
for FILE in $FILES; do
	for I in "${EXTENSION[@]}"
	do
		if [[ $FILE = ${I} ]]; then
		#echo "extension estatica detectada - - - > ${I}"
		RESULT="true"
		fi
	done
done
if [ "$RESULT" == "true" ] ; then
	IDCOMMIT=$(set -f; git log -1 --format=%h)
	git log -1 --format=%h > last_commit
	git add .
	git commit -m "update last_commit to: $IDCOMMIT" --no-verify
	echo -e ""
	echo -e "update last_commit to: $IDCOMMIT"
	echo -e ""
	exit 0
fi