#!/usr/bin/env node
/*
* versionador de estaticos + compressor
* Author: @jansanchez
* version: 0.1
*/

var fs = require("fs")
	, exec = require("child_process").exec
    , extensions = ["css", "js", "png", "jpg", "gif"]
    , hasStatic = false
    , commitFile = "src/last_commit"
    , gruntTask = "grunt produccion"
    , gruntPath = '/home/jan/htdocs/urbania3/frontend/grunt';

console.log(' + Ejecutando Hook...');

function execute(command, callback){
    exec(command, function(error, stdout, stderr){ callback(stdout); });
};

module.exports.getLastCommit = function(callback){
    var commit = {};
    execute("git rev-list --max-count=1 HEAD", function(last){
        commit.last = last.replace("\n", "");
        execute("git rev-list --max-count=1 HEAD~1", function(penultimate){
            commit.penultimate = penultimate.replace("\n", "");
            var diff = "git diff "+commit.last+" "+commit.penultimate+" --name-only";
            execute(diff, function(files){
                files = files.replace(/\n/gi, ',');
                files = files.substr(0, files.length-1);
                commit.files = files.split(',');
                callback(commit);
            });
        });
    });
};

module.exports.getLastCommit(function(obj){
    //console.log(obj.files);
    for (var i = 0; i < obj.files.length; i++) {
        if (/\.js$|\.css$|\.jpg$|\.png$|\.gif$/.test(obj.files[i])){
            hasStatic = true;
            break;
        }
    };
    if (hasStatic) {
    	console.log("   - extensiones estaticas detectadas.");
		console.log('   - inicio de minificacion de estaticos.');

		exec(gruntTask, {
			cwd: gruntPath
		}, function (err, stdout, stderr) {
			console.log(stdout);
			var exitCode = 0;
			if (err) {
				console.log(stderr);
				exitCode = -1;
				process.exit(exitCode);
			}else{
				console.log('   - fin de minificacion de estaticos.');
				execute("git log -1 --format=%h", function(idCommit){
					idCommit = idCommit.replace(/\n/gi, '');
					//console.log(idCommit);
					fs.writeFile(commitFile, idCommit, function(err) {
						if(err) {
							console.log(err);
						} else {
							var msg = 'update "'+commitFile+'" to ' + idCommit;
							execute("git add .; git commit -m \""+msg+"\" ", function(){
								console.log("   - "+msg);
								process.exit(exitCode);
							});
						}
					});
				});
			}			
		});
    };
});